spring:
  application:
    name: MvcChatApp
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: hakim@123

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  session:
    timeout: 7d

server:
  port: 9093
  compression:
    enabled: true
    min-response-size: 10KB
    mime-types: text/html, text/css, text/javascript, text/xml, application/font-woff, application/json, image/jpeg, image/png, image/svg+xml, video/mp4

default:
  user:
    image:
      folder: /user/
      name: user.svg
  message:
    image:
      folder: /message/
  pagination:
    size: 100

logging:
  file:
    path: logs
  level:
    root: warn

# Socket
app:
  socket:
    endpoint: /ws
    app_prefix: /
    user_prefix: /user