spring:
  application:
    name: MvcChatApp

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: hakim@123

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  servlet:
    session:
      timeout: 2h
  port: 9093

default:
  user:
    image:
      folder: /user/
      name: user.svg
  pagination:
    size: 100

logging:
  file:
    path: logs
  level:
    root: warn

# Socket
app:
  socket:
    endpoint: /ws
    app_prefix: /chat
    user_prefix: /user