#spring:
#  application:
#    name: MvcChatApp
#    # Threading
#  threads:
#    virtual:
#      enabled: true
#      # Database
#  datasource:
#    url: jdbc:postgresql://localhost:5432/chat_app
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: hakim@123
#
#  # JPA Properties
#  jpa:
#    hibernate:
#      ddl-auto: none # Enable when needed
#    open-in-view: false
#    # Session Properties
#  session:
#    timeout: 7d
#  # Caching resources
#  web:
#    resources:
#      chain:
#        enabled: true
#        strategy:
#          content:
#            enabled: true
#            paths: /**
#      cache:
#        period: 7d
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
## Server Properties
#server:
#  port: 9093
#  # Compressing static resources
#  compression:
#    enabled: true
#    min-response-size: 10KB
#    mime-types: text/html, text/css, text/javascript, text/xml, application/font-woff, application/json, image/jpeg, image/png, image/svg+xml, video/mp4
#
## Custom App properties
#default:
#  user:
#    image:
#      folder: /user/
#      name: user.svg
#  message:
#    image:
#      folder: /message/
#  group:
#    image:
#      folder: /group/
#      name: group.png
#    message:
#      image:
#        folder: /group/message/
#  pagination:
#    size: 100
#
## logging properties
#logging:
#  file:
#    path: logs
#  level:
#    root: warn
#
## Custom Socket properties
#app:
#  socket:
#    endpoint: /ws
#    app_prefix: /
#    user_prefix: /user
#    personal_message_channel: /queue/messages

spring:
  application:
    name: MvcChatApp
    # Threading
  threads:
    virtual:
      enabled: true
      # Database
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: none # Enable when needed
    open-in-view: false
    # Session Properties
  session:
    timeout: 7d
  # Caching resources
  web:
    resources:
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        period: 7d

# Server Properties
server:
  port: ${PORT}
  # Compressing static resources
  compression:
    enabled: true
    min-response-size: 10KB
    mime-types: text/html, text/css, text/javascript, text/xml, application/font-woff, application/json, image/jpeg, image/png, image/svg+xml, video/mp4

# Custom App properties
default:
  user:
    image:
      folder: /user/
      name: user.svg
  message:
    image:
      folder: /message/
  group:
    image:
      folder: /group/
      name: group.png
    message:
      image:
        folder: /group/message/
  pagination:
    size: 100

# logging properties
logging:
  file:
    path: logs
  level:
    root: warn

# Custom Socket properties
app:
  socket:
    endpoint: /ws
    app_prefix: /
    user_prefix: /user
    personal_message_channel: /queue/messages